/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.rj.macae.femass.receitas.gui;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;


    
/**
 *
 * @author RaquelYan
 */
public class TelaPrincipalGUI extends javax.swing.JFrame {

    
    
    public TelaPrincipalGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        mReceita = new javax.swing.JMenuItem();
        mCategoria = new javax.swing.JMenuItem();
        mIngrediente = new javax.swing.JMenuItem();
        mSobre = new javax.swing.JMenu();
        Sobre = new javax.swing.JMenuItem();
        mSair = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cookbook");
        setBackground(new java.awt.Color(51, 0, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 102, 0));
        setLocation(new java.awt.Point(400, 200));
        setMinimumSize(new java.awt.Dimension(640, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 51, 255));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(190, 140, 160, 140);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(300, 110, 170, 130);

        jLabel5.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cookbook");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 240, 108, 39);

        menu.setText("Menu");

        mReceita.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        mReceita.setText("Receitas");
        mReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mReceitaActionPerformed(evt);
            }
        });
        menu.add(mReceita);

        mCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        mCategoria.setText("Categorias");
        mCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCategoriaActionPerformed(evt);
            }
        });
        menu.add(mCategoria);

        mIngrediente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        mIngrediente.setText("Ingredientes");
        mIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIngredienteActionPerformed(evt);
            }
        });
        menu.add(mIngrediente);

        jMenuBar1.add(menu);

        mSobre.setText("Sobre");

        Sobre.setText("Sobre");
        Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreActionPerformed(evt);
            }
        });
        mSobre.add(Sobre);

        jMenuBar1.add(mSobre);

        mSair.setText("Sair");

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        mSair.add(Sair);

        jMenuBar1.add(mSair);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("Receitas CookBook");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void mReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mReceitaActionPerformed

        ReceitaGUI tela = new ReceitaGUI();
        tela.setVisible(true);
        
    }//GEN-LAST:event_mReceitaActionPerformed

    private void SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreActionPerformed
        JOptionPane.showMessageDialog(null,"Realizado por: Yan Moraes\nDisciplina:DSI\nProfessora:Ana Moura\nData:Outubro/2017\nVersão:1.0");
        // TODO add your handling code here:
    }//GEN-LAST:event_SobreActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void mCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCategoriaActionPerformed
        CategoriaGUI tela = new CategoriaGUI();
        tela.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_mCategoriaActionPerformed

    private void mIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIngredienteActionPerformed
        IngredienteGUI tela = new IngredienteGUI();
        tela.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_mIngredienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenuItem Sobre;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem mCategoria;
    private javax.swing.JMenuItem mIngrediente;
    private javax.swing.JMenuItem mReceita;
    private javax.swing.JMenu mSair;
    private javax.swing.JMenu mSobre;
    private javax.swing.JMenu menu;
    // End of variables declaration//GEN-END:variables

    
    
    
    
    

   
    

}
